### ISSUE TITLE
 'BOARD' object has no attribute 'GetModules'

### ISSUE THREAD

**Issue by par1111** [royalcrab/BBLED_LEDPanel#1]
i am having this error whenever i try to execute code.
please help

`  pcb = pcbnew.GetBoard()
AttributeError: 'BOARD' object has no attribute 'GetModules'`

**Comment by royalcrab** [comment]
> i am having this error whenever i try to execute code. please help
> 
> ` pcb = pcbnew.GetBoard() AttributeError: 'BOARD' object has no attribute 'GetModules'`

The following code can work on KiCad 5.x/6.x PCB editor console (not schematic editor)

```
import pcbnew
board = pcbnew.GetBoard()
```
